[package]
name = "brain"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
generated = { path = "../../generated" }
kameo = { version = "0.22", default-features = false, features = ["macros"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
cbor2 = { version = "*", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
dashmap = "6"
statig ="*"
