[package]
name = "ps4_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../common" }
generated = { path = "../../generated" }
kameo = { version = "0.22", default-features = false, features = ["macros"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
hidapi = "2"
